# Generated by Django 4.2.1 on 2023-05-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(default='Lj9Tzg', max_length=6),
        ),
    ]
