# Generated by Django 4.2.1 on 2023-05-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_status_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_task_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
